services:
  redis:
    image: redis:7.2
    container_name: redis-server
    volumes:
      - redis_data:/data

  blog-back:
    build: .
    container_name: blog-back
    ports:
      - "3010:3004" 
    depends_on:
      - redis
    env_file:
      - .env
    command: ["npm", "start"]

volumes:
  redis_data:
    driver: local
